version: '3'
services:
  slsart:
    image: slsart
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/home/node/artillery
    working_dir: /home/node/artillery
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
