version: '3'
services:
  slsart:
    image: slsart
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/home/node/artillery
    - ~/.aws/:/home/node/.aws:ro
    working_dir: /home/node/artillery
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
